modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/Wrenchest/blob/1.20/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Wrenchest/issues"

[[mods]]
	modId="wrenchest"
	version="${file.jarVersion}"
	displayName="Wrenchest"
	description='''Makes it easy to connect chests together!'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wrenchest"
	authors="bl4ckscor3"

[[dependencies.wrenchest]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wrenchest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"