modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/Wrenchest/blob/1.20.6/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Wrenchest/issues"

[[mods]]
	modId="wrenchest"
	version="${file.jarVersion}"
	displayName="Wrenchest"
	description='''Makes it easy to connect chests together!'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wrenchest"
	authors="bl4ckscor3"

[[dependencies.wrenchest]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wrenchest]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"